import { Container, Flex } from "@mantine/core";
import Head from "next/head";
import Body from "../components/Body";
import CardList from "../components/CardList";
import IncomeTable from "../components/Table";
import { Overview } from "@components/charts/overview";
import { RecentTransaction } from "@components/RecentTransactions";
import { useSelector } from "react-redux";
import { cn } from "lib/utils";
import Shell from "@components/shared/Shell";

export default function DashboardPage() {
  const sidebar = useSelector((state) => state.sidebar.visible);
  return (
    <div>
      <Head>
        <title>Expense | Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body>
        <CardList />
        <div className="w-full px-4 flex flex-col lg:flex-row gap-4">
          <Shell title="Overview" className="grow">
            <Overview />
          </Shell>
          <Shell>
            <RecentTransaction />
          </Shell>
        </div>
        <IncomeTable title={"Recent Transactions"} />
      </Body>
    </div>
  );
}
