import Head from "next/head";
import InputCard from "../components/forms";
import Body from "../components/Body";
import PageTitle from "../components/PageTitle";
import IncomeTable from "../components/Table";
import BarChart from "../components/BarChart";
import Shell from "@components/shared/Shell";
import MyAreaChart from "@components/charts/area-chart";
import { IncomeForm, InputCardHeader } from "@components/forms/income-form";

export default function Home() {
  return (
    <div className="flex flex-col">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body>
        <PageTitle title={"Expense"} link={"/expense"} />

        <div className="flex flex-col lg:flex-row gap-4 p-4">
          <Shell className="w-full max-w-lg">
            <InputCardHeader title={"Add income"} />
            <IncomeForm />
          </Shell>
          <Shell title="Income vs Expense" className="flex-1">
            <MyAreaChart />
          </Shell>
        </div>
        <IncomeTable title={"Recent Expense"} />
      </Body>
    </div>
  );
}
