import Head from "next/head";
import Login from "../components/Login";
import { useProfileQuery } from "redux/api/userApiSlice";
import { useEffect } from "react";
import { useRouter } from "next/router";
import { useDispatch } from "react-redux";
import { setUser } from "redux/slices/authSlice";

function LoginPage() {
  const { data: user, isSuccess } = useProfileQuery();
  const router = useRouter();
  const dispatch = useDispatch();

  useEffect(() => {
    if (isSuccess) {
      dispatch(setUser({ user }));
      router.back();
      router.push("/dashboard");
    }
  }, [isSuccess]);

  return (
    <div>
      <Head>
        <title>Expenditure | Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="font-roboto">
        <Login />
      </div>
    </div>
  );
}

export default LoginPage;
