import Head from "next/head";
import Body from "../components/Body";
import WorkingOnIt from "../components/WorkingOnIt";
import GettingStarted from "../components/GettingStarted";

export default function OnBoarding() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gradient-to-r from-rose-100 to-teal-100 h-screen flex justify-center items-center">
        <GettingStarted />
      </main>
    </div>
  );
}
