import Head from "next/head";
import Body from "../components/Body";
import OnBoarding from "../components/onboarding";
import Image from "next/image";
import { useRouter } from "next/router";
import { useProfileQuery } from "redux/api/userApiSlice";
import { setUser } from "redux/slices/authSlice";
import { useEffect } from "react";
import { useSelector } from "react-redux";

export default function OnBoardingPage() {
  const user = useSelector((state) => state.auth.user);
  const router = useRouter();
  useEffect(() => {
    if (!user) {
      console.log("NO user", user);
      // router.push("/login");
    }
    if (user && user.onboarding) {
      console.log("user is on boarded", user);
      // router.push("/dashboard");
    }
  }, [user]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative h-screen flex justify-center items-center bg-gray-100">
        <OnBoarding />
      </main>
    </div>
  );
}
